title: NoFlo
tagline: Flow-Based Programming for JavaScript
version: 0.8.1
permalink: /:categories/:title/
baseurl: ""
repository:
  web: "https://github.com/noflo/noflo"
  git: "git://github.com/noflo/noflo.git"
google:
  search: "016364845905675673706:orufl0szkhw"
  analytics: "UA-75936-14"
  plus: "u/0/112372998187205178398"
highlight_libraries:
  - noflo-couchdb
  - noflo-diffbot
  - noflo-ducksboard
  - noflo-github
  - noflo-stripe
  - noflo-redis
  - noflo-twilio
  - noflo-twitter
libraries:
  - noflo/noflo-adapters
  - kenhkan/noflo-automaton
  - noflo/noflo-basecamp
  - kenhkan/noflo-cache
  - robingl/noflo-calc
  - kenhkan/noflo-compare
  - noflo/noflo-core
  - noflo/noflo-couchdb
  - robingl/noflo-csv
  - noflo/noflo-diffbot
  - noflo/noflo-docco
  - kenhkan/noflo-crypto
  - noflo/noflo-ducksboard
  - noflo/noflo-filesystem
  - noflo/noflo-flow
  - noflo/noflo-git
  - noflo/noflo-github
  - noflo/noflo-gravatar
  - noflo/noflo-groups
  - kenhkan/noflo-handyman
  - noflo/noflo-html
  - noflo/noflo-lift
  - noflo/noflo-liquid
  - noflo/noflo-markdown
  - noflo/noflo-math
  - noflo/noflo-mq
  - noflo/noflo-objects
  - noflo/noflo-oembed
  - noflo/noflo-packets
  - kenhkan/noflo-pg
  - kenhkan/noflo-pgorm
  - noflo/noflo-physics
  - noflo/noflo-redis
  - noflo/noflo-restfulmetrics
  - noflo/noflo-routers
  - kenhkan/noflo-semanticsthree
  - noflo/noflo-strings
  - svetly/noflo-stripe
  - kenhkan/noflo-swiss
  - kenhkan/noflo-twilio
  - robingl/noflo-twitter
  - kenhkan/noflo-underscore
  - noflo/noflo-webserver
  - noflo/noflo-websocket
  - kenhkan/noflo-woute
  - noflo/noflo-xml
  - noflo/noflo-yaml
browser_libraries:
  - noflo/noflo-ajax
  - noflo/noflo-core
  - noflo/noflo-css
  - noflo/noflo-dom
  - noflo/noflo-flow
  - noflo/noflo-interaction
  - noflo/noflo-localstorage
  - noflo/noflo-math
  - noflo/noflo-objects
  - noflo/noflo-physics
  - noflo/noflo-routers
  - noflo/noflo-strings
  - d4tocchini/noflo-draggabilly
  - noflo/noflo-websocket
exclude:
  - "node_modules"
  - "Gruntfile.coffee"
  - "README.md"
  - "npm-debug.log"
  - "package.json"
  - "docco.css"
  - "Gemfile"
  - "Gemfile.lock"
gems:
  - jekyll-redirect-from
